client/.babelrc
client/package-lock.json
client/package.json
client/src/index.js
client/webpack.config.js

- resolved #2 
Webpack과 babel을 설정했습니다.

chore: Setup webpack and babel.

---

client/package-lock.json
client/package.json
client/src/components/Button.css
client/src/components/Button.js
client/src/components/Element.js
client/src/components/Header.css
client/src/components/Header.js
client/src/components/List.js
client/src/components/__test__/Button.test.js
client/src/index.js
client/src/reset.css

클래스를 이용해 페이지를 렌더하는 것을 한번 생각해 보았어요. 버튼 테스트 코드도 한번 만들어 봤어요.
참고 #6

페이지 구조 만들기

---

server/package-lock.json
server/package.json
server/scripts/createTable.js

- resolved #11 
createTable.js 를 실행하면 ec2에 있는 DB에 테이블이 생성됩니다.

feat: ec2 DB 테이블 생성 스크립트 작성

---

client/src/components/Log.css
client/src/components/Log.js
client/src/components/Main.js
client/src/components/Menu.css
client/src/components/Menu.js
client/src/components/__tests__/Log.test.js
client/src/components/basic/Element.js
server/scripts/createTable.js

- resolved #31 
컴포넌트를 이용하여 메뉴 마크업 만들었습니다. 항상 보이는 상태. 기능동작 X

메뉴 마크업 만들기

---

client/src/components/Main.js
client/src/components/Todo.css
client/src/components/Todo.js
client/src/components/global.scss

- resolved #33 
- 쓰레기통 버튼을 누르면 alert를 띄웁니다.
- 전체 카드를 더블클릭해도 alert를 띄웁니다.
- global style에 .flex-grow-1을 추가했습니다.
- flex-grow: 1 을 설정합니다.
- Change parameter of todo element constructor to object style.

Todo 마크업 만들기

---

server/app.js
server/babel.config.js
server/package-lock.json
server/package.json
server/routes/__test__/index.test.js
server/routes/index.js
server/routes/users.js

- resolved #40 
백엔드 테스트 세팅  
> npm test  
입력시 jest를 이용한 테스트 실행

백엔드 테스트 세팅

---

client/src/components/Main.js
client/src/components/basic/Element.js
client/src/components/basic/Modal.js
client/src/components/basic/Modal.scss
client/src/components/global.scss

- resolved #46
- 메인 화면에서 show modal 버튼을 클릭하면 테스트 모달이 생깁니다.
- 배경을 누르면 모달이 사라집니다.
- 하지만 모달창을 눌러도 모달이 사라지지 않습니다.
- 하지만 모달창 안의 "x"를 누르면 모달이 사라집니다.
- 글로벌 스타일을 수정했습니다.
- 버튼 스타일 리셋 배경화면 수정
- flex-spacebetween 추가
- new Modal(title, content)를 하면 모달이 생깁니다.

모달 컴포넌트 만들기

---

client/src/components/Column.js
client/src/components/Column.scss
client/src/components/basic/Input.js
client/src/components/basic/Textarea.js

- resolved #36  
입력창 마크업 제작했습니다.
텍스트 영역은 우측 하단 드래그하면 세로 높이 조절 가능
width="500px">

feat: todo 입력 마크업 제작

---

server/initDb.sh
server/scripts/createTable.js
server/scripts/insertTestData.js
server/scripts/sendQueries.js

- 테이블을 만드는 함수를 둘로 나눴습니다.
- 테스트 데이터를 추가하는 스크립트를 만들었습니다: `node ./scripts/insertTestData.js` in /server

테스트 데이터 추가하는 스크립트 만들기

---

client/src/components/Column.js
client/src/components/Column.scss
client/src/components/basic/Button.js
client/src/components/basic/Textarea.js
client/src/components/global.scss

- resolved #51 
button-form, button-green, button-grey 글로벌 css 로 빼냄.
todo 입력 Wrapper div를 form 으로 변경

refactor: form button과 관련된 css 분리, NewTodoWrapper->NewTodoForm 으로 변경

---

client/src/components/Column.js
client/src/components/Column.scss
client/src/components/Main.js
client/src/components/ModalTodoEdit/index.js
client/src/components/global.scss

- resolved #37 
- form 스타일 클래스를 글로벌로 바꾸었습니다.
- todo 수정 모달을 만들었습니다.
- 메인 페이지의 모달 테스트 버튼을 too 수정 모달로 바꿔었습니다.

투두 수정 모달을 추가했습니다.

---

docker/mysql/init.sql
server/scripts/createTable.js
server/scripts/insertTestData.js

todo_column table의 title을 content로 바꿈에 따라 여러 sql에 있는
title을 content로 바꿨습니다.

fix: DB 스키마 변화에 따른 적응

---

docker/mysql/init.sql
server/routes/apis/deleteTodoApi.js
server/routes/index.js

- resolved #15 
- db 에서 투두를 삭제합니다.
- 도커 db 초기화 sql에서 오타를 고쳤습니다.

두투 삭제 api 구현

---

server/routes/apis/columnsApi.js

오타 수정했습니다.
content -> nextColumnContent
함수명 수정했습니다.
isValid -> isValidAll (파라미터가 전부 조건을 만족하면 true 인 느낌으로...)

fix: isValid -> isValidAll,  함수 안 변수명 content -> nextColumnConent

---

client/src/components/Column/index.js
client/src/components/FormModal/index.js
client/src/components/Menu/index.js
client/src/components/ModalColumnTitleEdit/index.js
client/src/components/Todo/index.js
server/routes/apis/addTodoApi.js
server/routes/apis/columnsApi.js

- resolved #23 
- 컬럼이름을 더블클릭하면 모달을 띄웁니다.
- 0자 초과, 50자 미만이면 버튼을 비활성화 시킵니다.
- 수정을 하면 서버 api call을 하고 컬럼 이름을 바꾸고 로그를 더합니다.

클라이언트 컬럼 이름 수정 구현

---

client/src/components/Column/index.js
client/src/components/Todo/index.js
docker/mysql/init.sql
server/routes/apis/deleteTodoApi.js

- resolved #89
Todo remove 시 db log 저장
db: log table의 actin_type의 최대 길이를 20으로 바꾸었습니다. 왜냐하면 action_type의 길이가 6을 넘기 때문에...

Todo remove 시 db log 저장

---

client/src/components/Column/Column.scss
client/src/components/Column/NewTodoForm.js
client/src/components/Column/index.js
client/src/components/global.scss
client/src/lib/apiCallWrapper.js
server/routes/apis/addTodoApi.js
server/routes/apis/loadTodosApi.js

- resolved #66 
프론트엔드에서 todo 추가하는 기능들 구현.
상세 내용은 이슈 확인 바랍니다.

feat: todo 추가 기능 구현

---

server/routes/apis/deleteTodoApi.js

fix: remove todo에서 inserted log id를 반환

---

server/routes/apis/addTodoApi.js

feat: todo 추가시 로그를 DB에 저장함

---

client/src/components/Menu/index.js
client/src/lib/apiCallWrapper.js
server/routes/apis/loadLogsApi.js
server/routes/index.js

- resolved #16 resolved #93 
초기화 화면에서 로그 불러오고 렌더하기.
메뉴가 초기화 될 때 server api call을 부릅니다.

초기화 화면에서 로그 불러오고 렌더하기

---

server/routes/apis/editTodoApi.js
server/routes/index.js

투두 내용을 수정하고 로그를 돌려줍니다.
- resolved #18

todo edit api implementation

---

client/src/components/Column/Column.scss
client/src/components/Column/index.js

Column에 flex 속성을 적용하여
Todo Input form이 생겼을때 todo list의 높이가 자동으로 변경되게 설정

fix: column에 flex 적용해서 todo add form 동적 높이에 따라서 todo list 높이 자동 변경

---

client/src/components/Todo/index.js
client/src/lib/apiCallWrapper.js
server/routes/apis/editTodoApi.js

- resolved #99 , resolved #18 
프론트엔드에서 todo 수정 버튼 눌렀을때
todo 수정, log 기록 로직 작성했습니다.

feat: todo edit frontend 로직

---

client/src/components/Main.js

fix: 테스트 버튼 제거했습니다.

---

client/src/components/TodoDrag/DragPlaceholder.js
client/src/components/TodoDrag/TodoDrag.css
client/src/components/TodoDrag/index.js

fix: place holder 스타일을 todo 투명한 모습으로 변경

---

client/src/components/basic/Modal/Modal.scss
client/src/components/basic/ModalConfirm/ModalConfirm.scss
client/src/components/basic/ModalConfirm/index.js

투두 삭제 모달창 스타일링
- resolved #108

삭제 모달 창 스타일하기

---

client/src/components/Column/index.js
client/src/components/Todo/index.js
client/src/components/TodoDrag/index.js
client/src/components/basic/Element.js
client/src/lib/apiCallWrapper.js

- resolved #24 
투두 옮기면 api 호출하고
로그에 기록합니다.

feat: 프론트엔드에서 todo card 옮길 때 api 호출하는 로직 작성

---

client/src/components/Todo/index.js

Fixes #113
- resolved #113 
mousedown 이벤트 핸들러에서 왼쪽 버튼인지 확인하고 아니면 무시합니다.

todo mousedown 오른쪽 클릭 검사

---

client/src/components/Column/index.js
client/src/components/Menu/Menu.css
client/src/components/Menu/index.js
client/src/lib/apiCallWrapper.js

feat: column 삭제 프론트엔드 로직

---

client/src/components/Column/NewTodoForm.js
client/src/components/Column/index.js
client/src/components/Menu/index.js
client/src/components/global.scss

fix: issue #130
